spring.application.name=proj06-PaymentGatewayProfileSystem-1


//spring.profiles.active=phonepe
spring.profiles.active=gpay

//payment.companyName=PhonePe Pvt Ltd
payment.companyName=Googlepe Pvt Ltd
payment.transactionLimit=50000
payment.paymentType=UPI
