spring.application.name=proj05-HospitalFullCollectionInjection-5


hospital.id=900
hospital.name=Care Hospital

hospital.doctors[0]=Ravi
hospital.doctors[1]=Kiran

hospital.specialists[0]=Cardiology
hospital.specialists[1]=Neurology

hospital.staff.cleaner=20
hospital.staff.nurse=45