spring.application.name=proj07-NotificationServiceProfile-2


spring.profiles.active=email

#notification.senderName=Email Service Team
#notification.supportEmail=support@email.com
#notification.notificationType=EMAIL

notification.senderName=SMS Service Team
notification.supportEmail=support@sms.com
notification.notificationType=SMS